baseurl = "https://rawktron.github.io/"
title = "rawktron"
theme = "hugo-creative-portfolio"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "sea"
  description = "rawktron.com"
  copyright = "&copy;2017 Pete Garcin"
  sidebarAbout = [
    "Pete Garcin. Developer Advocate @ActiveState. Long time games industry vet, audio director, musician, writer.",
    "You can find my projects and writing here."
  ]
  # Contact page
     # Since this template is static, the contact form uses www.formspree.io as a
     # proxy. The form makes a POST request to their servers to send the actual
     # email. Visitors can send up to a 1000 emails each month for free.
     #
     # What you need to do for the setup?
     #
     # - set your email address under 'email' below
     # - upload the generated site to your server
     # - send a dummy email yourself to confirm your account
     # - click the confirm link in the email from www.formspree.io
     # - you're done. Happy mailing!
  #email = "you@yoursite.com"

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Home"
  url = ""

  [[params.navlinks]]
  name = "About"
  url = "about/"


  [params.social]
#  facebook      = "full page or profile url in facebook"
#  googleplus    = "full profile url in googleplus"
#  email         = "email@example.com"
  twitter       = "https://twitter.com/rawktron"
  github        = "https://github.com/rawktron"
  stackoverflow = "http://stackoverflow.com/users/7753940/rawktron"
  instagram     = "https://www.instagram.com/rawktron/"
  linkedin      = "https://www.linkedin.com/in/petegarcin/"
